### PR TITLE
Sanitize filename before upload to prevent issues with spaces and special characters in filenames.

### PR DESCRIPTION
**Pull request by larskarbo**
I noticed that uploads with spaces in the filename gave invalid urls.

shot-dGIGz1p0

The problem seems to be that `req.body.filename` in `s3-upload.ts` for some reason has filename spaces encoded with `%20` instead of a space.

And when you upload to s3 with `%20` in the url you have to add `%2520` to get the actual url.

Returned by library: `https://XXX/filename%20with-one-space.png`
Actual working url (from aws console): `https://XXX/filename%2520with-one-space.png`

This PR does two things:
1. Remove `encodeURIComponent` of the filename on the client side. Send the real, unencoded filename to the back-end.
2. On the back-end, sanitize the filename and remove all characters not supported by s3.

### CODE REVIEW

**Comment by ryanto** [comment]
100% Agree.  👍 

I'd like to avoid having a dependency on that library if possible, also don't think we need the latin character remapping.

What do you think about something like this? https://codesandbox.io/s/laughing-murdock-w1xusx, trying to keep the sanitization as simple as possible here.

**Comment by larskarbo** [comment]
That's sleek @ryanto! I updated the PR with that solution. Let me know if you think it looks all right.

I think it makes sense to give the un-sanitized filename to the `options.key` function.

Tested locally with space and special chars. Works like a charm!

**Comment by ryanto** [comment]
Looks great!

**Comment by ryanto** [comment]
Ok published at `0.2.7`

Thanks again for adding this!

**Pull request merged**
