### PR TITLE
Add Route for Next App Directory

### PR DESCRIPTION
**Pull request by martinmiglio**
This PR adds an export for a route handler to be used in the latest NextJS App router.

The changes include abstracting out the functionality of the original page router and updating the handler to have a type of `type NextAppRouteHandler = (req: NextRequest) => Promise<Response>;` to match the described syntax of the App Router's [Route Handlers](https://nextjs.org/docs/app/building-your-application/routing/route-handlers#convention).
With this change of type, the way responses are made is changed, using `NextReponse.json()` and `NextResponse.error()`

To implement this route in the App router, something like the following would be used:
```ts
// app/api/s3-upload/route.ts

import { AppAPIRoute, sanitizeKey } from "next-s3-upload";

export const POST = AppAPIRoute.configure({
  key(req, filename) {
    return `images/${sanitizeKey(filename)}`;
  },
});

```

Relates to #154

### CODE REVIEW

**Comment by ryanto** [comment]
Awesome thank you for this PR and getting it added! I'm a little hesitant to duplicating the code because we have a lot of tests that cover various uploads and we'd need to also duplicate those. I agree that an abstraction it the right approach, do you want to take a shot at doing that? Happy to answer any questions or help!

**Comment by martinmiglio** [comment]
I've reduced most of the code duplication, extracted it out into `utils/route-builder.ts`.
Still need some work done to make the route options maintain the existing API as well as update the tests for these changes.
Let me know what you think so far @ryanto

**Comment by ryanto** [comment]
Oh awesome, it's looking good! Thanks for doing this, I know that part of the code can be narly with all the config/options everywhere!

👍 Yup I think we should support the existing API so people upgrading don't have to touch their existing pages/api/s3-upload.ts files. Looks like your code will support that though.

Let me know when you want me to take a look and test it. I can take care of adding the automated tests... since I want to create a new Next 13 test app and use it there.

Thanks again for adding this, really appreciate it!

**Comment by martinmiglio** [comment]
Everything looks ready for review, let me know if you want me to write/update any tests or docs.

**Comment by devandnow** [comment]
> Everything looks ready for review, let me know if you want me to write/update any tests or docs.

Happy to help out testing as well - we have an app being ported to app-router at the mo.

**Comment by martinmiglio** [comment]
@devandnow I would love some more testing on this!

Also just cleaned up the error responses, not sure if I like the `console.error`'s but I don't want errors to go by quietly.

**Comment by devandnow** [comment]
> Also just cleaned up the error responses, not sure if I like the `console.error`'s but I don't want errors to go by quietly.

Agree - consolling on the api route will be super helpful whilst everyone settles into the app-router methods.

**Comment by devandnow** [comment]
This all works for me - I tested on a /pages and this new method and didn't notice any major differences so I 'think' all good to go

**Comment by thomasmorice** [comment]
@martinmiglio cheers for that, I need it as well 👍

**Comment by ryanto** [comment]
Ok next-s3-upload should now be usable with the app router in version `0.3.4`.

Here's all you need:

```tsx
// app/api/s3-upload/route.js
export { POST } from "next-s3-upload/route";
```

Huge thanks to @martinmiglio for making this happen!

**Pull request merged**
