### PR TITLE
make aws credentials optional

### PR DESCRIPTION
**Pull request by manuelsechi**

### CODE REVIEW

**Comment by manuelsechi** [comment]
@ryanto I dont really understand how to make my project to point to this branch for testing. I tried to change it in package.json but seems not to work
```
"next-s3-upload": "make-aws-credential-optional",
```
any hint?

**Comment by ryanto** [comment]
Try...

```json
"next-s3-upload": "manuelsechi/next-s3-upload#make-aws-credential-optional",
```

**Comment by manuelsechi** [comment]
I can't get this installed correctly, as it is creating a folder like
```
node_modules/next-s3-upload/packages/next-s3-upload/src
```
while your package is
```
node_modules/next-s3-upload/src
```

**Comment by ryanto** [comment]
Ah right, you'll have to build the package. Check out the contributing docs here: https://next-s3-upload.codingvalue.com/contributing. Running `yarn build` will compile your source code.

I'm a little swamped with work these days, so I can't really be of much help unfortunately. If I were in your shoes I think I would build and publishing your fork as your own npm package and then try to use that on your EC2 servers.

**Pull request closed without merging**
